-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "Games" (
    "RECORD_ID" int not null,
    "SEASON_ID" int   NOT NULL,
    "HOME_TEAM_ID" int   NOT NULL,
    "GAME_ID" int   NOT NULL,
    "GAME_DATE" date   NOT NULL,
    "HOME_PTS" int   NOT NULL,
    "HOME_FGM" int   NOT NULL,
    "HOME_FGA" int   NOT NULL,
    "HOME_FG_PCT" numeric   NOT NULL,
    "HOME_FG3M" int   NOT NULL,
    "HOME_FG3A" int   NOT NULL,
    "HOME_FG3_PCT" numeric   NOT NULL,
    "HOME_FTM" int   NOT NULL,
    "HOME_FTA" int   NOT NULL,
    "HOME_FT_PCT" numeric   NOT NULL,
    "HOME_OREB" int   NOT NULL,
    "HOME_DREB" int   NOT NULL,
    "HOME_REB" int   NOT NULL,
    "HOME_AST" int   NOT NULL,
    "HOME_STL" int   NOT NULL,
    "HOME_BLK" int   NOT NULL,
    "HOME_TOV" int   NOT NULL,
    "HOME_PF" int   NOT NULL,
    "HOME_PLUS_MINUS" numeric   NOT NULL,
    "HOME_WIN" int   NOT NULL,
    "AWAY_TEAM_ID" int   NOT NULL,
    "AWAY_PTS" int   NOT NULL,
    "AWAY_FGM" int   NOT NULL,
    "AWAY_FGA" int   NOT NULL,
    "AWAY_FG_PCT" numeric   NOT NULL,
    "AWAY_FG3M" int   NOT NULL,
    "AWAY_FG3A" int   NOT NULL,
    "AWAY_FG3_PCT" numeric   NOT NULL,
    "AWAY_FTM" int   NOT NULL,
    "AWAY_FTA" int   NOT NULL,
    "AWAY_FT_PCT" numeric   NOT NULL,
    "AWAY_OREB" int   NOT NULL,
    "AWAY_DREB" int   NOT NULL,
    "AWAY_REB" int   NOT NULL,
    "AWAY_AST" int   NOT NULL,
    "AWAY_STL" int   NOT NULL,
    "WAY_BLK" int   NOT NULL,
    "AWAY_TOV" int   NOT NULL,
    "AWAY_PF" int   NOT NULL,
    "AWAY_PLUS_MINUS" numeric  NOT NULL
);

